### ISSUE TITLE
This is great! Do you have any ideas / intent to implement the ❌  elements in future?

### ISSUE THREAD

**Issue by crisdosaygo** [lissomware/css#2]
I've perused a lot of these classless CSS guys and yours is really up my ally. I really like it! Look professional and confident and solid.

It's an interesting UX/UI/design problem to get really good default styling on complex things like DL/DD/DT, DETAILS/SUMMARY, METER etc. If you intend to do so, I hope you achieve it! I look forward to using this.

Sorry for the dumb question, I know it's not your job to just help out noobs like me -- but I'm pretty new to static site blogs like jekyll -- would it be too much to ask you how I would include this in my Jekyll blog?

**Comment by Looky1173** [comment]
Yes, I would certainly like to tackle the ❌ elements in the future. I added a legend below the table to clarify the meaning of the symbols.

Unfortunately, I'm not really familial with Jekyll, it has been ages since I've last used it (I've switched to other solutions for various reasons). However, this [StackOverflow](https://stackoverflow.com/a/32723763) answer might help. You could either download `lissom.min.css` from this repository and update it periodically when I push updates, or you could use always use the latest version with [this direct link](https://lissomware.github.io/css/lissom.min.css). Let me know how it goes!

**Comment by crisdosaygo** [comment]
Thank you, friend! 😊🥹😃

**Comment by umitseyhan75** [comment]
Any news on this @Looky1173?
